import axios from 'axios'

const api = axios.create({ baseURL: '/api', timeout: 5000 })
// Longer timeout for WSL commands that may take up to 2 minutes
const apiWsl = axios.create({ baseURL: '/api', timeout: 130000 })
const apiGraphify = axios.create({ baseURL: '/api', timeout: 620000 })
// Measured detailed-list baseline was ~1.6s before compact list rows; 5s keeps
// a deliberate >3x margin without hiding queue starvation behind a long wait.
const apiQueue = axios.create({ baseURL: '/api', timeout: 5000 })

export const getHealth = () => api.get('/health').then(r => r.data)
export const getEntities = () => api.get('/entities').then(r => r.data)
export const getOverview = () => api.get('/overview').then(r => r.data)
export const getLogs = () => api.get('/logs').then(r => r.data)
export const getResults = () => api.get('/results').then(r => r.data)
export const getPackets = () => api.get('/packets').then(r => r.data)
export const getTracker = () => api.get('/tracker').then(r => r.data)
export const getConnectors = () => api.get('/connectors').then(r => r.data)
export const getComposioConnections = () => api.get('/composio/connections').then(r => r.data)
export const getQueueSummary = () => apiQueue.get('/queue/summary').then(r => r.data)
export const getQueueStatus = () => apiQueue.get('/queue/status').then(r => r.data)
export const getQueueItems = () => apiQueue.get('/queue/items').then(r => r.data)
export const getQueueItemsForScope = scope => api.get('/queue/items', { params: { scope } }).then(r => r.data)
export const getQueueItem = (id) => apiQueue.get(`/queue/items/${id}`).then(r => r.data)
export const getQueueNext = () => apiQueue.get('/queue/next').then(r => r.data)
export const getQueueReceipt = (path) => apiQueue.get('/queue/receipt', { params: { path } }).then(r => r.data)
export const getQueueArtifact = (path) => apiQueue.get('/queue/artifact', { params: { path } }).then(r => r.data)
export const openQueueArtifactFolder = (path) => apiQueue.post('/queue/artifact/open-folder', { path }).then(r => r.data)
export const createQueueItem = (data) => apiQueue.post('/queue/items', data).then(r => r.data)
export const createQueueChain = (data) => apiQueue.post('/queue/chains', data).then(r => r.data)
export const getQueuePrompt = (id, target) => apiQueue.get(`/queue/items/${id}/prompt`, { params: { target } }).then(r => r.data)
export const attachQueueReceipt = (id, data) => apiQueue.post(`/queue/items/${id}/receipt`, data).then(r => r.data)
export const saveQueueReviewNote = (id, data) => apiQueue.post(`/queue/items/${id}/review-note`, data).then(r => r.data)
export const closeQueueItemReview = (id, data) => apiQueue.post(`/queue/items/${id}/review-close`, data).then(r => r.data)
export const updateQueueItemStatus = (id, status) => apiQueue.post(`/queue/items/${id}/status`, { status }).then(r => r.data)
export const runQueueItem = (id) => apiQueue.post(`/queue/items/${id}/run`, {}, { timeout: 620000 }).then(r => r.data)
export const updateTracker = (data) => api.post('/tracker', data).then(r => r.data)
export const createPacket = (data) => api.post('/packets', data).then(r => r.data)
export const launchEntity = (id) => api.post(`/launchers/${id}/launch`).then(r => r.data)

// WSL / AgenticOSClean runtime
export const wslStatus = () => apiWsl.get('/wsl/status').then(r => r.data)
export const wslHermes = (task) => apiWsl.post('/wsl/hermes', { task }).then(r => r.data)
export const wslClaude = (task) => apiWsl.post('/wsl/claude', { task }).then(r => r.data)
export const wslCodex = (task) => apiWsl.post('/wsl/codex', { task }).then(r => r.data)
export const getHermesUiStatus = () => api.get('/hermes-ui/status').then(r => r.data)
export const launchHermesUi = () => apiWsl.post('/hermes-ui/launch').then(r => r.data)

export const telegramStatus = () => api.get('/connectors/telegram/status').then(r => r.data)
export const getBackupsStatus = () => api.get('/backups/status').then(r => r.data)
export const getDashboardCockpit = () => api.get('/dashboard/cockpit').then(r => r.data)
export const createCockpitCommand = (command) => api.post('/dashboard/cockpit/command', { command }).then(r => r.data)
export const createInboxCapture = (text, capture_id) => api.post('/dashboard/capture', { text, capture_id }).then(r => r.data)
export const getDashboardTokens = () => api.get('/dashboard/tokens').then(r => r.data)
export const getDashboardResults = () => api.get('/dashboard/results', { timeout: 20000 }).then(r => r.data)
export const getDashboardAgents = () => api.get('/dashboard/agents').then(r => r.data)
export const getDashboardSystemWatch = (stalledMinutes = 15) => api.get('/dashboard/system-watch', { params: { stalled_minutes: stalledMinutes } }).then(r => r.data)
export const getLatitudeStatus = () => api.get('/latitude/status').then(r => r.data)
export const sendLatitudeHeartbeat = () => api.post('/latitude/heartbeat').then(r => r.data)
export const sendAgentMailDigest = (data = {}) => api.post('/agentmail/daily-digest', data).then(r => r.data)
export const externalActionDryRun = (data) => api.post('/external-actions/dry-run', data).then(r => r.data)
export const routeMessageBoardCommand = (data) => api.post('/dashboard/message-board/route', data).then(r => r.data)
export const askHermesMessage = (text, source_refs = []) => apiWsl.post('/hermes/message', { text, source_refs }).then(r => r.data)
export const getDashboardWorkflows = () => api.get('/dashboard/workflows').then(r => r.data)
export const getDashboardWorkflow = (id) => api.get(`/dashboard/workflows/${encodeURIComponent(id)}`).then(r => r.data)
export const saveDashboardWorkflow = (data) => api.post('/dashboard/workflows/save', data).then(r => r.data)
export const getWorkflowContracts = () => api.get('/dashboard/workflow-contracts').then(r => r.data)
export const getDashboardSkills = () => api.get('/dashboard/skills').then(r => r.data)
export const getDashboardMemory = () => api.get('/dashboard/memory').then(r => r.data)
export const getDashboardPrompts = () => api.get('/dashboard/prompts').then(r => r.data)
export const getDashboardGraphify = () => api.get('/dashboard/graphify').then(r => r.data)
export const getDashboardRepoIngest = () => api.get('/dashboard/repo-ingest').then(r => r.data)
export const fetchGraphifyRepository = (url) => apiGraphify.post('/graphify/fetch', { url }).then(r => r.data)
export const refetchGraphifyRepository = (url) => apiGraphify.post('/graphify/refetch', { url }).then(r => r.data)
export const rebuildGraphifyRepository = (owner, repository) => apiGraphify.post('/graphify/rebuild', { owner, repository }).then(r => r.data)
export const runGraphifyAction = (owner, repository, action, inputs) => apiGraphify.post('/graphify/action', { owner, repository, action, inputs }).then(r => r.data)
export const queueGraphifyModelWork = (owner, repository, requested_work) => api.post('/graphify/queue-model-work', { owner, repository, requested_work }).then(r => r.data)
export const getGraphifyArtifactText = (url) => apiGraphify.get(url.replace(/^\/api/, ''), { responseType: 'text', transformResponse: value => value }).then(r => r.data)
export const createDashboardTask = (data) => api.post('/dashboard/create-task', data).then(r => r.data)
export const saveDashboardSkill = (data) => api.post('/dashboard/skills/save', data).then(r => r.data)
export const openDashboardPath = (data) => api.post('/dashboard/open-path', data).then(r => r.data)
export const searchIndex = (params) => api.get('/search', { params: { client_scope: 'global', ...params } }).then(r => r.data)
export const getSearchStatus = () => api.get('/search/status').then(r => r.data)
export const reindexSearch = () => api.post('/search/reindex').then(r => r.data)
export const ingestTick = () => api.post('/ingest/tick').then(r => r.data)
export const getArtifacts = (params) => api.get('/artifacts', { params: { client_scope: 'global', ...params } }).then(r => r.data)
