import axios from 'axios'

const api = axios.create({ baseURL: '/api', timeout: 5000 })
// Longer timeout for WSL commands that may take up to 2 minutes
const apiWsl = axios.create({ baseURL: '/api', timeout: 130000 })

export const getHealth = () => api.get('/health').then(r => r.data)
export const getEntities = () => api.get('/entities').then(r => r.data)
export const getOverview = () => api.get('/overview').then(r => r.data)
export const getLogs = () => api.get('/logs').then(r => r.data)
export const getResults = () => api.get('/results').then(r => r.data)
export const getPackets = () => api.get('/packets').then(r => r.data)
export const getTracker = () => api.get('/tracker').then(r => r.data)
export const getConnectors = () => api.get('/connectors').then(r => r.data)
export const getComposioConnections = () => api.get('/composio/connections').then(r => r.data)
export const getQueueSummary = () => api.get('/queue/summary').then(r => r.data)
export const getQueueStatus = () => api.get('/queue/status').then(r => r.data)
export const getQueueItems = () => api.get('/queue/items').then(r => r.data)
export const getQueueItem = (id) => api.get(`/queue/items/${id}`).then(r => r.data)
export const getQueueNext = () => api.get('/queue/next').then(r => r.data)
export const getQueueReceipt = (path) => api.get('/queue/receipt', { params: { path } }).then(r => r.data)
export const getQueueArtifact = (path) => api.get('/queue/artifact', { params: { path } }).then(r => r.data)
export const createQueueItem = (data) => api.post('/queue/items', data).then(r => r.data)
export const createQueueChain = (data) => api.post('/queue/chains', data).then(r => r.data)
export const getQueuePrompt = (id, target) => api.get(`/queue/items/${id}/prompt`, { params: { target } }).then(r => r.data)
export const attachQueueReceipt = (id, data) => api.post(`/queue/items/${id}/receipt`, data).then(r => r.data)
export const closeQueueItemReview = (id, data) => api.post(`/queue/items/${id}/review-close`, data).then(r => r.data)
export const updateQueueItemStatus = (id, status) => api.post(`/queue/items/${id}/status`, { status }).then(r => r.data)
export const updateTracker = (data) => api.post('/tracker', data).then(r => r.data)
export const createPacket = (data) => api.post('/packets', data).then(r => r.data)
export const launchEntity = (id) => api.post(`/launchers/${id}/launch`).then(r => r.data)

// WSL / AgenticOSClean runtime
export const wslStatus = () => apiWsl.get('/wsl/status').then(r => r.data)
export const wslHermes = (task) => apiWsl.post('/wsl/hermes', { task }).then(r => r.data)
export const wslClaude = (task) => apiWsl.post('/wsl/claude', { task }).then(r => r.data)
export const wslCodex = (task) => apiWsl.post('/wsl/codex', { task }).then(r => r.data)

export const telegramStatus = () => api.get('/connectors/telegram/status').then(r => r.data)
export const getBackupsStatus = () => api.get('/backups/status').then(r => r.data)
export const getDashboardCockpit = () => api.get('/dashboard/cockpit').then(r => r.data)
export const getDashboardTokens = () => api.get('/dashboard/tokens').then(r => r.data)
export const getDashboardResults = () => api.get('/dashboard/results').then(r => r.data)
export const getDashboardAgents = () => api.get('/dashboard/agents').then(r => r.data)
export const getDashboardSystemWatch = (stalledMinutes = 15) => api.get('/dashboard/system-watch', { params: { stalled_minutes: stalledMinutes } }).then(r => r.data)
export const getLatitudeStatus = () => api.get('/dashboard/latitude/status').then(r => r.data)
export const sendLatitudeHeartbeat = () => api.post('/dashboard/latitude/heartbeat').then(r => r.data)
export const sendAgentMailDigest = (data = {}) => api.post('/agentmail/daily-digest', data).then(r => r.data)
export const externalActionDryRun = (data) => api.post('/external-actions/dry-run', data).then(r => r.data)
export const routeMessageBoardCommand = (data) => api.post('/dashboard/message-board/route', data).then(r => r.data)
export const askHermesMessage = (text, source_refs = []) => apiWsl.post('/hermes/message', { text, source_refs }).then(r => r.data)
export const getDashboardWorkflows = () => api.get('/dashboard/workflows').then(r => r.data)
export const getWorkflowContracts = () => api.get('/dashboard/workflow-contracts').then(r => r.data)
export const getDashboardSkills = () => api.get('/dashboard/skills').then(r => r.data)
export const getDashboardMemory = () => api.get('/dashboard/memory').then(r => r.data)
export const getDashboardPrompts = () => api.get('/dashboard/prompts').then(r => r.data)
export const getDashboardGraphify = () => api.get('/dashboard/graphify').then(r => r.data)
export const getDashboardRepoIngest = () => api.get('/dashboard/repo-ingest').then(r => r.data)
export const createDashboardTask = (data) => api.post('/dashboard/create-task', data).then(r => r.data)
export const saveDashboardSkill = (data) => api.post('/dashboard/skills/save', data).then(r => r.data)
export const openDashboardPath = (data) => api.post('/dashboard/open-path', data).then(r => r.data)
export const searchIndex = (params) => api.get('/search', { params }).then(r => r.data)
export const getSearchStatus = () => api.get('/search/status').then(r => r.data)
export const reindexSearch = () => api.post('/search/reindex').then(r => r.data)
export const ingestTick = () => api.post('/ingest/tick').then(r => r.data)
export const getArtifacts = (params) => api.get('/artifacts', { params }).then(r => r.data)
